# Generated by Django 6.0.1 on 2026-02-14 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_student_studentclass'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parent',
            old_name='name',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='name',
            new_name='user',
        ),
    ]
